'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Correio

    '''<summary>
    '''lblMensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensagem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkRecebidas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRecebidas As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkEnviadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkEnviadas As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkNovaMensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNovaMensagem As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''imgIconeTipoMensagens control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgIconeTipoMensagens As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblMsgEnvRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgEnvRec As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlMensagensRecebidas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMensagensRecebidas As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucMensRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucMensRec As Global.UTFPR.SGTCC.WebInterface.GridMensagensRecebidas

    '''<summary>
    '''pnlMensagensEnviadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMensagensEnviadas As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ucMensEnv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucMensEnv As Global.UTFPR.SGTCC.WebInterface.GridMensagensEnviadas
End Class
