'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class GridGerenciarTcc

    '''<summary>
    '''gdvGerenciarTcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvGerenciarTcc As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlPaginacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPaginacao As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPagAtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPagAtual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalPag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalPag As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkAnterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAnterior As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkProxima control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProxima As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hdntema control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdntema As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnstatus01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnstatus01 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnstatus02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnstatus02 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnstatus03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnstatus03 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnstatus04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnstatus04 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnstatus05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnstatus05 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnmatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnmatricula As Global.System.Web.UI.WebControls.HiddenField
End Class
