'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class menu

    '''<summary>
    '''menuHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuHome As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkHome As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''menuMateria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuMateria As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkMateria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkMateria As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''menuAgenda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuAgenda As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkAgenda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAgenda As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''menuCorreio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuCorreio As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkCorreio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCorreio As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''menuUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuUsuarios As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkUsuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkUsuarios As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''menuTcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuTcc As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkTcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTcc As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''menuAvisos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuAvisos As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkAvisos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAvisos As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''menuArquivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuArquivos As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkArquivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkArquivos As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''menuConfig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuConfig As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkConfig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkConfig As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''menuDownloads control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuDownloads As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkDownloads control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDownloads As Global.System.Web.UI.WebControls.LinkButton
End Class
