'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class UrlMaps
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UTFPR.SGTCC.WebInterface.UrlMaps", GetType(UrlMaps).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Agenda.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Agenda() As String
            Get
                Return ResourceManager.GetString("Agenda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Configuracoes.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Configuracoes() As String
            Get
                Return ResourceManager.GetString("Configuracoes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Correio.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Correio() As String
            Get
                Return ResourceManager.GetString("Correio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/DatasImportantes.aspx.
        '''</summary>
        Friend Shared ReadOnly Property DatasImportantes() As String
            Get
                Return ResourceManager.GetString("DatasImportantes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Defesa.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Defesa() As String
            Get
                Return ResourceManager.GetString("Defesa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/DefinirCoordenador.aspx.
        '''</summary>
        Friend Shared ReadOnly Property DefinirCoordenador() As String
            Get
                Return ResourceManager.GetString("DefinirCoordenador", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Download.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Download() As String
            Get
                Return ResourceManager.GetString("Download", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Downloads.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Downloads() As String
            Get
                Return ResourceManager.GetString("Downloads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/EditarAviso.aspx.
        '''</summary>
        Friend Shared ReadOnly Property EditarAviso() As String
            Get
                Return ResourceManager.GetString("EditarAviso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/EditarBanca.aspx.
        '''</summary>
        Friend Shared ReadOnly Property EditarBanca() As String
            Get
                Return ResourceManager.GetString("EditarBanca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/EditarTCC.aspx.
        '''</summary>
        Friend Shared ReadOnly Property EditarTCC() As String
            Get
                Return ResourceManager.GetString("EditarTCC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/EventoAgenda.aspx.
        '''</summary>
        Friend Shared ReadOnly Property EventoAgenda() As String
            Get
                Return ResourceManager.GetString("EventoAgenda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/GerenciarArquivos.aspx.
        '''</summary>
        Friend Shared ReadOnly Property GerenciarArquivos() As String
            Get
                Return ResourceManager.GetString("GerenciarArquivos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/GerenciarAvisos.aspx.
        '''</summary>
        Friend Shared ReadOnly Property GerenciarAvisos() As String
            Get
                Return ResourceManager.GetString("GerenciarAvisos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/GerenciarBanca.aspx.
        '''</summary>
        Friend Shared ReadOnly Property GerenciarBanca() As String
            Get
                Return ResourceManager.GetString("GerenciarBanca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/GerenciarTCC.aspx.
        '''</summary>
        Friend Shared ReadOnly Property GerenciarTCC() As String
            Get
                Return ResourceManager.GetString("GerenciarTCC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/GerenciarUsuarios.aspx.
        '''</summary>
        Friend Shared ReadOnly Property GerenciarUsuarios() As String
            Get
                Return ResourceManager.GetString("GerenciarUsuarios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Home.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Home() As String
            Get
                Return ResourceManager.GetString("Home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Login.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Login() As String
            Get
                Return ResourceManager.GetString("Login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/mainTCC.aspx.
        '''</summary>
        Friend Shared ReadOnly Property mainTCC() As String
            Get
                Return ResourceManager.GetString("mainTCC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Materia.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Materia() As String
            Get
                Return ResourceManager.GetString("Materia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/NovaBanca.aspx.aspx.
        '''</summary>
        Friend Shared ReadOnly Property NovaBanca() As String
            Get
                Return ResourceManager.GetString("NovaBanca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/NovaMensagem.aspx.
        '''</summary>
        Friend Shared ReadOnly Property NovaMensagem() As String
            Get
                Return ResourceManager.GetString("NovaMensagem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/NovoAviso.aspx.
        '''</summary>
        Friend Shared ReadOnly Property NovoAviso() As String
            Get
                Return ResourceManager.GetString("NovoAviso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/NovoTCC.aspx.
        '''</summary>
        Friend Shared ReadOnly Property NovoTCC() As String
            Get
                Return ResourceManager.GetString("NovoTCC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/NovoUsuario.aspx.
        '''</summary>
        Friend Shared ReadOnly Property NovoUsuario() As String
            Get
                Return ResourceManager.GetString("NovoUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Orientadores.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Orientadores() As String
            Get
                Return ResourceManager.GetString("Orientadores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Perfil.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Perfil() As String
            Get
                Return ResourceManager.GetString("Perfil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Proposta.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Proposta() As String
            Get
                Return ResourceManager.GetString("Proposta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/RecuperarSenha.aspx.
        '''</summary>
        Friend Shared ReadOnly Property RecuperarSenha() As String
            Get
                Return ResourceManager.GetString("RecuperarSenha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Relatorios.aspx.
        '''</summary>
        Friend Shared ReadOnly Property Relatorios() As String
            Get
                Return ResourceManager.GetString("Relatorios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/RelatoriosPorData.aspx.
        '''</summary>
        Friend Shared ReadOnly Property RelatoriosPorData() As String
            Get
                Return ResourceManager.GetString("RelatoriosPorData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Situacao.aspx.
        '''</summary>
        Friend Shared ReadOnly Property SituacaoAluno() As String
            Get
                Return ResourceManager.GetString("SituacaoAluno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/VisualizarAviso.aspx.
        '''</summary>
        Friend Shared ReadOnly Property VisualizarAviso() As String
            Get
                Return ResourceManager.GetString("VisualizarAviso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/VisualizaRelatorio.aspx.
        '''</summary>
        Friend Shared ReadOnly Property VisualizaRelatorio() As String
            Get
                Return ResourceManager.GetString("VisualizaRelatorio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/VisualizarMensagem.aspx.
        '''</summary>
        Friend Shared ReadOnly Property VisualizarMensagem() As String
            Get
                Return ResourceManager.GetString("VisualizarMensagem", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
