'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class GerenciarBanca

    '''<summary>
    '''lblAluno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAluno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOrientador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrientador As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTema control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTema As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnNovaBanca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNovaBanca As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlProposta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProposta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblLocalProposta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocalProposta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConvidado01Proposta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConvidado01Proposta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConvidado02Proposta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConvidado02Proposta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDataProposta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataProposta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnDeletarProposta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeletarProposta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAlterarProposta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAlterarProposta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlDefesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDefesa As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblLocalDefesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocalDefesa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConvidado01Defesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConvidado01Defesa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConvidado02Defesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConvidado02Defesa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDataDefesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataDefesa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnDeletarDefesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeletarDefesa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAlterarDefesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAlterarDefesa As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensagem As Global.System.Web.UI.WebControls.Label
End Class
